### PR TITLE
implement HeaderMapKey only for static strings

### PR DESCRIPTION
**Pull request by seanmonstar**
This is a possible solution for #72. This makes it so you can only use `&'static str` (besides `HeaderName`) as a key, and thus any panics are because of static strings with illegal characters. This much more closely matches the idea of panics should be for programmer errors.

**DO NOT MERGE YET.** I'm going to open another PR showing a very different solution that removes the panics completely, and we can compare.

### CODE REVIEW

**Comment by carllerche** [comment]
As mentioned in IRC, the point of implementing `HeaderMapKey` on more types is to enable the ability to avoid the `K` -> `HeaderName` conversion when the key already exists in the map.

**Comment by alexcrichton** [comment]
@carllerche just to make sure I understand, this means that a lookup which previously is:

```rust
let a = String::from("...");
foo.insert(&a, ...);
```

Previously we won't allocate a `HeaderName` because it's already in the map, but after this we're forced to look up with a `HeaderName` or a `&HeaderName`, where creating one of those from a `String` forces an allocation?

**Comment by seanmonstar** [comment]
@alexcrichton for insert, it doesn't really matter. It must make an owned `HeaderName` to store as a key in the map. However, searching for keys shouldn't really need to parse and allocate a `HeaderName`.

In this PR, that would be required.

```rust
// before
map.get(&some_custom_name)

// after
let name = some_custom_name.parse().unwrap();
map.get(&name)
```

#86 explores a different solution. Since searching just requires a hash and then a comparison, `"evil\r\nname"` should never be found in the map, so `map.get("evil\r\nname").is_none()` should always be true, and not need to panic.

**Comment by carllerche** [comment]
It definetly does matter for insertion as @alexcrichton pointed out. Currently, If the map already contains the key, the example will not allocate. With this change, it would need to as the HeaderName needs to be constructed before passing to insert.

**Comment by carllerche** [comment]
I think this PR has been superseded by #86?

**Comment by seanmonstar** [comment]
#86 is the better solution, closing.

**Pull request closed without merging**
